version: '3.8'
volumes:
  mysql_db:

services:
  mysql_db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    image: berg1005/todo_list
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
